
[package]
edition = "2018"
name = "transpiled"
version = "0.1.0"
authors = ["automatically transpiled by serpent"]

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
csv = "1.1.3"
statrs = "0.13.0"
